.TH LIBVIRT-MIGRATE-XEND-MANAGED-DOMAINS: "1" "" "April 2014" "April 2014"

.SH NAME
libvirt\-migrate\-xend\-managed\-domains \- program for migrating xend managed domains
.PP
.SH DESCRIPTION
Xend, which was used together with the (deprecated) xm toolstack allowed to
define managed domains. Those were kept in a separate place and could get
automatically started on boot (as well as automatically suspended to disk
on shutdown). However the new xl toolstack has no such support.
This script is intended to convert machine definitions in the xen-sxpr
format over to xml definitions in libvirt.

Only machines which (their name) does not already exist in for the
libxl driver are converted.

.SH USAGE
.TP
libvirt\-migrate\-xend\-managed\-domains

.SH FILES
.TP
/var/lib/libvirt/xend\-migration\-done
.PP
Migration will not be done again as long as that file exists (the content
does not matter).
.TP
/var/lib/xend/domains
.PP
That directory contains the original xend definitions. Each guest in a
subdirectory named after its uuid. The uuid subdirectories can and should
be deleted when the migration was successful.

.SH BUGS
.PP
Convertion can only be done when running as dom0, using the xl toolstack.

.SH SEE ALSO
.PP
\fBvirsh\fR(1)

.SH AUTHOR
.PP
libvirt\-migrate\-xend\-managed\-domains is Copyright 2014, Canonical Ltd.

.PP
by Stefan Bader <stefan\&.bader@canonical\&.com>.
